### ISSUE TITLE
Integration rpi_power not found when trying to verify its sensor platform.

### ISSUE THREAD

**Issue by iliDaedalus** [custom-components/sensor.rpi_power#17]
This error message first appeared after updating to HA 0.92.0  

I also get it with one more custom_component.
The difference of those non-working-anymore, compared with those working is the __init__.py which doesn't exist on the non-working.

I've updated the rpi_power/sensor.py with the latest but the problem remains.

**Comment by PrathikGopal** [comment]
Component wont work in hass 0.92.0, crashes HASSIO for me

**Comment by nickm324** [comment]
Same issue, no longer works since updating to 0.92.0 was working prior to that version 0.91.4 I think. What changed?

**Comment by nickm324** [comment]
Added a new pull request to fix this.

**Comment by swetoast** [comment]
tnx nickm324 your fix is added

**Comment by nickm324** [comment]
> tnx nickm324 your fix is added

Glad I could contribute.
