### ISSUE TITLE
Does this component work with custom_updater?

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-components/sensor.rpi_power#24]
If so, does it need a string to be added to "component_urls:"
If not, any change this will be supported?

**Comment by swetoast** [comment]
ask @ludeeus

**Comment by ludeeus** [comment]
<https://github.com/custom-components/information/blob/a65d4c6825dd64ef04b6acc383423c23f24be188/repos.json#L438-L449>
Works without any addition.
