### ISSUE TITLE
Wrong processing of RasPi output

### ISSUE THREAD

**Issue by aluisperezh** [custom-components/sensor.rpi_power#25]
As someone stated before, the component is not adequately processing the throttling values. The messages I'm receiving in HA log are like this:

` WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.rpi_power_status=There is a problem with your power supply or system.; value=50000, friendly_name=RPi Power status, icon=mdi:raspberry-pi @ 2019-06-20T08:44:49.042226+02:00> (Offending entity: There is a problem with your power supply or system.)`

I know this means there is problem with the PSU (a new one is in its way), but by reading the code the displayed message should be 

`The Raspberry Pi is throttled due to a bad power supply this can lead to corruption and instability, please replace your changer and cables.`

For some reason the value is being read as text and processed as a number. Or at least that is the message in the log, I don't know enough Python to understand the code, sorry.

I'm using HA 0.94.4, but 0.94.3 behaved exactly the same. And, of course, the output from `cat /sys/devices/platform/soc/soc:firmware/get_throttled` is,as the log says, 50000.

Thanks

**Comment by swetoast** [comment]
your powersupply is faulty

**Comment by Beduir** [comment]
> I know this means there is problem with the PSU (a new one is in its way), but by reading the code the displayed message should be

That's how I solved the problem:
In the file sensor.py
Code
```
        _throttled = open(SYSFILE, 'r').read()[:-1]
```
replace to
```
        _throttled = open(SYSFILE, 'r').read()[:-1]
        _throttled = _throttled[:4]
```

**Comment by swetoast** [comment]
@Beduir mind sending a patch dont really have time to work on this project at all

**Comment by aluisperezh** [comment]
@Beduir Thank you very much. That did it
