### ISSUE TITLE
FEATURE: description translation

### ISSUE THREAD

**Issue by pejotigrek** [custom-components/sensor.rpi_power#30]
hi!

not an issue, rather a question/will to help ;)

is there any way to prepare translations for the value descriptions?
I know I could do a second template sensor, that would give informations in my local language [Polish] based on the value of the main sensor, but I don't want to make another entities, I like my config as clean and minimal as possible [wherever I can].

if you'd add multilanguage option [based on HA settings, or on given parameter] I can provide translation for Polish. I guess that others would be happy to help with different languages :)

**Comment by swetoast** [comment]
dont really have the project setup for translation but if you can provide a patch for it, ill be more then willing to merge it :)

**Comment by pejotigrek** [comment]
..if I only knew how to do that, it would be already done ;) unfortunately my programming skills are somewhere near NULL ;D
ok, so let's hope somebody capable sees my post and will help on the dev side :)

**Comment by swetoast** [comment]
i cant promise this feature in the near future hence why i pinned it if someone has the time else im gonna look into when my schedule is less demanding :)

**Comment by metbril** [comment]
https://developers.home-assistant.io/docs/en/internationalization_backend_localization.html

**Comment by BartEngelen** [comment]
Following this !
Translation to Dutch will also be great

**Comment by groenmarsmannetje** [comment]
I also would like to have it in Dutch. Willing to translate, just share the different texts.
