### ISSUE TITLE
rpi_power not found

### ISSUE THREAD

**Issue by Altar82** [custom-components/sensor.rpi_power#33]
Hi, im trying to add this custom component, but return this issue:

Integration rpi_power not found when trying to verify its sensor platform

With hassio 96.5
U can fix it? Ty

**Comment by swetoast** [comment]
you need all the files not just the py file

**Comment by Altar82** [comment]
Ty for your answer
I put all the file.. Manifest.json,_inti_.py,sensor.py in a folder:
config/custom_component/rpi_power
Are there any other files I haven't seen?

**Comment by swetoast** [comment]
since im not running HA at all these days support might be limited, dunno if there has been some changes in the lastest versions try downgrading to see if it works in an older version, if it does then its some change that they did yet again.

**Comment by Altar82** [comment]
Ty for your answer... I forced restart HA and it worked

**Comment by swetoast** [comment]
hmm ok :+1: great news ill add a comment to the read me on the instructions on forcing a restart
