### ISSUE TITLE
Error code ffff

### ISSUE THREAD

**Issue by codeclinic** [custom-components/sensor.rpi_power#36]
I'm using an x735 power management board on my Pi with and x825 usb drive adapter with a supposedly decent power supply. For a good 12+hrs after booting the power supply is indicated as "Everything is working ok". However at some point this will flip to "There is a problem with your power supply or system".

This message isn't in the readme as an expected output, so I ran `vcgencmd get_throttled` which returns: `throttled=0x0`. So that shows no throttling has occurred which is a good sign.

If I then run `cat /sys/devices/platform/soc/soc:firmware/get_throttled` it returns a value of `ffff`. Any ideas what this means? A reboot of the system returns the value to = / Everything is ok.

**Comment by swetoast** [comment]
ask on the rpi forums havent seen that code before so  im unsure
