### ISSUE TITLE
Replace power supply when sensor detects a problem in just 1% of the time?

### ISSUE THREAD

**Issue by nelbs** [custom-components/sensor.rpi_power#38]
I installed the sensor and I noticed that in 99% of the time the state of the sensor is "everything is working as intended".  Sometimes the state changes to "Your Raspberry Pi is limited due to a bad power supply, replace the power supply".

How should I interpret this advice? Is it better to change the power supply or is it normal that this happen sometimes

Thanks!

**Comment by swetoast** [comment]
this isnt an issue your powersupply is telling you something. is going bad it it might be a good time to start thinking about a new one,
