### ISSUE TITLE
Get throttled issue

### ISSUE THREAD

**Issue by blyons16** [custom-components/sensor.rpi_power#39]
I just stumbled onto this handy component. Thanks so much for creating it. I don't know for sure if this is related, but ran a dmesg in the ssh console, and saw this:

> [46252.366572] WARNING: CPU: 3 PID: 14519 at drivers/firmware/raspberrypi.c:212 get_throttled_show+0x68/0x6c
[46252.369314] deprecated, use hwmon sysfs instead

Thoughts?

**Comment by swetoast** [comment]
rpi4 ? 
cause that isnt supported if it is

**Comment by blyons16** [comment]
No, it is a 3b+, running HassOS 3.13, HA core 0.108.8.  Sorry, I should have included that the first time.

**Comment by swetoast** [comment]
well i need some more info like kernel version etc to move forward cause my rpi3b+ doesnt display this 

so mind giving me `uname -r`

**Comment by swetoast** [comment]
@popcornmix have you guys made any changes to calling for get throttled lately ?

**Comment by blyons16** [comment]
uname -r
4.19.114-v7

Also, to provide a little more context, this is the dmesg section right
before and after the warning:

[   66.325110] udevd[181]: starting version 3.2.9
[   66.367388] udevd[182]: starting eudev-3.2.9
[   66.808862] Under-voltage detected! (0x00050005)
[   73.048611] Voltage normalised (0x00000000)
[  109.889082] ------------[ cut here ]------------
[  109.890502] WARNING: CPU: 2 PID: 4406 at
drivers/firmware/raspberrypi.c:212 get_throttled_show+0x68/0x6c
[  109.893224] deprecated, use hwmon sysfs instead
[  109.894573] Modules linked in: nf_conntrack_netlink nfnetlink xfrm_user
xfrm_algo aes_arm_bs crypto_simd cryptd algif_skcipher af_alg bnep hci_uart
btbcm serdev bluetooth ecdh_generic joydev evdev sch_fq_codel uas cdc_acm
spidev raspberrypi_hwmon hwmon brcmfmac brcmutil cfg80211 snd_bcm2835(C)
snd_pcm bcm2835_codec(C) snd_timer bcm2835_v4l2(C) rfkill v4l2_mem2mem snd
i2c_bcm2835 bcm2835_mmal_vchiq(C) videobuf2_vmalloc videobuf2_dma_contig
videobuf2_memops spi_bcm2835 videobuf2_v4l2 videobuf2_common vc_sm_cma(C)
uio_pdrv_genirq uio fixed
[  109.904160] CPU: 2 PID: 4406 Comm: python3 Tainted: G         C
 4.19.114-v7 #1
[  109.906860] Hardware name: BCM2835

The "Under-voltage detected...Voltage normalized" messages right before the
warning make me wonder. This one is before the get_throttled_show and
appears to be 6.239749 seconds. All of the messages after are less than 5
seconds.  I noticed that your automation notification has "after 5 seconds"
in it. Is this normal, and why you have the 5 second wait in your
automation, or am I on the edge of a problem?

Thanks for your help!
bl

**Comment by swetoast** [comment]
well you are on the edge, but that doesn't count out the issue at hand with the deprecated message

**Comment by blyons16** [comment]
Thanks. Please pardon my ignorance, but what does "tainted" mean in this context?

**Comment by swetoast** [comment]
its using older code to execute the task mind giving me your python version also

`python -v`

**Comment by popcornmix** [comment]
See https://github.com/raspberrypi/linux/pull/2706

**Comment by swetoast** [comment]
tnx @popcornmix will change to this

**Comment by popcornmix** [comment]
From the linked PR: 
> Per hwmon sysfs in0_lcrit_alarm must be boolean.

So you only get under-voltage.

The other bits are pi specific so you may be better off with ``vcgencmd get_throttled`` if you need them all.

**Comment by blyons16** [comment]
in SSH:
Our command line:
$ ha help
➜  ~ python -v
zsh: command not found: python
➜  ~

In console:
# python -v
/bin/ash python not found

I don't understand. What am I missing?

bl

**Comment by blyons16** [comment]
I think I see the problem. I have python3, not python:
➜  ~ python3 -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class
'_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /usr/lib/python3.8/encodings/__pycache__/__init__.cpython-38.pyc matches
/usr/lib/python3.8/encodings/__init__.py
# code object from
'/usr/lib/python3.8/encodings/__pycache__/__init__.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/codecs.cpython-38.pyc matches
/usr/lib/python3.8/codecs.py
# code object from '/usr/lib/python3.8/__pycache__/codecs.cpython-38.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at
0x76cb0bb0>
# /usr/lib/python3.8/encodings/__pycache__/aliases.cpython-38.pyc matches
/usr/lib/python3.8/encodings/aliases.py
# code object from
'/usr/lib/python3.8/encodings/__pycache__/aliases.cpython-38.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader
object at 0x76cc8b68>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at
0x76cb0aa8>
# /usr/lib/python3.8/encodings/__pycache__/utf_8.cpython-38.pyc matches
/usr/lib/python3.8/encodings/utf_8.py
# code object from
'/usr/lib/python3.8/encodings/__pycache__/utf_8.cpython-38.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader
object at 0x76cb04d8>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.8/encodings/__pycache__/latin_1.cpython-38.pyc matches
/usr/lib/python3.8/encodings/latin_1.py
# code object from
'/usr/lib/python3.8/encodings/__pycache__/latin_1.cpython-38.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader
object at 0x76cc8c88>
# /usr/lib/python3.8/__pycache__/io.cpython-38.pyc matches
/usr/lib/python3.8/io.py
# code object from '/usr/lib/python3.8/__pycache__/io.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/abc.cpython-38.pyc matches
/usr/lib/python3.8/abc.py
# code object from '/usr/lib/python3.8/__pycache__/abc.cpython-38.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at
0x76cc8fd0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at
0x76cc8e50>
# /usr/lib/python3.8/__pycache__/site.cpython-38.pyc matches
/usr/lib/python3.8/site.py
# code object from '/usr/lib/python3.8/__pycache__/site.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/os.cpython-38.pyc matches
/usr/lib/python3.8/os.py
# code object from '/usr/lib/python3.8/__pycache__/os.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/stat.cpython-38.pyc matches
/usr/lib/python3.8/stat.py
# code object from '/usr/lib/python3.8/__pycache__/stat.cpython-38.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at
0x76c70100>
# /usr/lib/python3.8/__pycache__/_collections_abc.cpython-38.pyc matches
/usr/lib/python3.8/_collections_abc.py
# code object from
'/usr/lib/python3.8/__pycache__/_collections_abc.cpython-38.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader
object at 0x76c701f0>
# /usr/lib/python3.8/__pycache__/posixpath.cpython-38.pyc matches
/usr/lib/python3.8/posixpath.py
# code object from '/usr/lib/python3.8/__pycache__/posixpath.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/genericpath.cpython-38.pyc matches
/usr/lib/python3.8/genericpath.py
# code object from
'/usr/lib/python3.8/__pycache__/genericpath.cpython-38.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object
at 0x76c84958>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at
0x76c70a30>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at
0x76cdb7a8>
# /usr/lib/python3.8/__pycache__/_sitebuiltins.cpython-38.pyc matches
/usr/lib/python3.8/_sitebuiltins.py
# code object from
'/usr/lib/python3.8/__pycache__/_sitebuiltins.cpython-38.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader
object at 0x76cdbec8>
# /usr/lib/python3.8/__pycache__/_bootlocale.cpython-38.pyc matches
/usr/lib/python3.8/_bootlocale.py
# code object from
'/usr/lib/python3.8/__pycache__/_bootlocale.cpython-38.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object
at 0x76c84b50>
# /usr/lib/python3.8/__pycache__/types.cpython-38.pyc matches
/usr/lib/python3.8/types.py
# code object from '/usr/lib/python3.8/__pycache__/types.cpython-38.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at
0x76c84d48>
# /usr/lib/python3.8/importlib/__pycache__/__init__.cpython-38.pyc matches
/usr/lib/python3.8/importlib/__init__.py
# code object from
'/usr/lib/python3.8/importlib/__pycache__/__init__.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/warnings.cpython-38.pyc matches
/usr/lib/python3.8/warnings.py
# code object from '/usr/lib/python3.8/__pycache__/warnings.cpython-38.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at
0x76ca02b0>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at
0x76ca00d0>
# /usr/lib/python3.8/importlib/__pycache__/util.cpython-38.pyc matches
/usr/lib/python3.8/importlib/util.py
# code object from
'/usr/lib/python3.8/importlib/__pycache__/util.cpython-38.pyc'
# /usr/lib/python3.8/importlib/__pycache__/abc.cpython-38.pyc matches
/usr/lib/python3.8/importlib/abc.py
# code object from
'/usr/lib/python3.8/importlib/__pycache__/abc.cpython-38.pyc'
# /usr/lib/python3.8/importlib/__pycache__/machinery.cpython-38.pyc matches
/usr/lib/python3.8/importlib/machinery.py
# code object from
'/usr/lib/python3.8/importlib/__pycache__/machinery.cpython-38.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader
object at 0x76ca0c88>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader
object at 0x76ca0748>
# /usr/lib/python3.8/__pycache__/contextlib.cpython-38.pyc matches
/usr/lib/python3.8/contextlib.py
# code object from
'/usr/lib/python3.8/__pycache__/contextlib.cpython-38.pyc'
# /usr/lib/python3.8/collections/__pycache__/__init__.cpython-38.pyc
matches /usr/lib/python3.8/collections/__init__.py
# code object from
'/usr/lib/python3.8/collections/__pycache__/__init__.cpython-38.pyc'
# /usr/lib/python3.8/__pycache__/operator.cpython-38.pyc matches
/usr/lib/python3.8/operator.py
# code object from '/usr/lib/python3.8/__pycache__/operator.cpython-38.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at
0x76c4e4f0>
# /usr/lib/python3.8/__pycache__/keyword.cpython-38.pyc matches
/usr/lib/python3.8/keyword.py
# code object from '/usr/lib/python3.8/__pycache__/keyword.cpython-38.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at
0x76c4e640>
# /usr/lib/python3.8/__pycache__/heapq.cpython-38.pyc matches
/usr/lib/python3.8/heapq.py
# code object from '/usr/lib/python3.8/__pycache__/heapq.cpython-38.pyc'
# extension module '_heapq' loaded from '/usr/lib/python3.8/lib-dynload/_
heapq.cpython-38-arm-linux-gnueabihf.so'
# extension module '_heapq' executed from '/usr/lib/python3.8/lib-dynload/_
heapq.cpython-38-arm-linux-gnueabihf.so'
import '_heapq' # <_frozen_importlib_external.ExtensionFileLoader object at
0x76c4eaa8>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at
0x76c4e6e8>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.8/__pycache__/reprlib.cpython-38.pyc matches
/usr/lib/python3.8/reprlib.py
# code object from '/usr/lib/python3.8/__pycache__/reprlib.cpython-38.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at
0x76c4eeb0>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object
at 0x76c375e0>
# /usr/lib/python3.8/__pycache__/functools.cpython-38.pyc matches
/usr/lib/python3.8/functools.py
# code object from '/usr/lib/python3.8/__pycache__/functools.cpython-38.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at
0x76c37688>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object
at 0x76ca0e38>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader
object at 0x76c84f88>
# possible namespace for /usr/lib/python3.8/site-packages/ruamel
import 'site' # <_frozen_importlib_external.SourceFileLoader object at
0x76cdb4d8>
Python 3.8.2 (default, Feb 29 2020, 17:03:31)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/usr/lib/python3.8/lib-dynload/
readline.cpython-38-arm-linux-gnueabihf.so'
# extension module 'readline' executed from '/usr/lib/python3.8/lib-dynload/
readline.cpython-38-arm-linux-gnueabihf.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object
at 0x76c5aa00>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.8/__pycache__/rlcompleter.cpython-38.pyc matches
/usr/lib/python3.8/rlcompleter.py
# code object from
'/usr/lib/python3.8/__pycache__/rlcompleter.cpython-38.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object
at 0x76c5aeb0>

**Comment by swetoast** [comment]
https://github.com/home-assistant/core/pull/35527

rpi power will probly get merged and the issue will get resolved by hassio devs :)
