### ISSUE TITLE
 No file SYSFILE = '/sys/class/hwmon/hwmon0/in0_lcrit_alarm'

### ISSUE THREAD

**Issue by Ikif** [custom-components/sensor.rpi_power#43]
Get error for the sensor. 
The file in0_lcrit_alarm not existed .

pi@raspberrypi:~ $ uname -r
5.4.51-v7l+

**Comment by swetoast** [comment]
downgrade to previous version

**Comment by Ikif** [comment]
How I download previous version ? Where I see other versions ?

**Comment by swetoast** [comment]
try the latest release
