### ISSUE TITLE
0.2.0 doesn't work

### ISSUE THREAD

**Issue by regystro** [custom-components/sensor.rpi_power#44]
I just updated from 0.1.5 to 0.2.0 and the sensor.rpi_power_status no longer appears in Home Assistant. It's missing in Developer Tools > States.

Sorry, but I've got no more info, since nothing appears on the logs. Tried reinstalling, but no luck. Only rolling back to 0.1.5 makes it work again.

Thank you.

**Comment by swetoast** [comment]
Read the updated read me it went from senor to binary_sensor

**Comment by regystro** [comment]
Sorry, I didn't notice the new readme you updated at the same time I posted this issue ;)

I miss the example configuration. Do you plan to add one?

Thanks again for such a great integration.

**Comment by metbril** [comment]
Why doesn't regular HACS updates take care of this all (except from changing my config from sensor to binary sensor)? I have 0.2.0 installed, with `sensor` but `0.2.1.` is not installed automatically.

**Comment by regystro** [comment]
Try choosing "master" (the last option of the dropdown list) instead of 0.2.0 when installing this module. It installs 0.2.1

Maybe the author will fix this when he finishes holidays.

**Comment by swetoast** [comment]
Won't fix read the open issue

**Comment by regystro** [comment]
By fixing I mean that you maybe should push the master version to appear as 0.2.1 in the dropdown list in the HACS integration installer. In fact, master `binary_sensor.py` already states `__version__ = '0.2.1'`. Otherwise people using HACS will continue installing 0.2.0 (the latest offered version) and having to search for issues not mentioned in the readme.

If don't want to "fix" this, I suggest you change in the readme "Manually download and install the files from the aforementioned URL into your custom_components\rpi_power" by "From HACS, choose "master" in the installation dropdown options. Otherwise manually download and install the master branch into your custom_components\rpi_power folder".

Another option is a link from readme to https://github.com/custom-components/sensor.rpi_power/issues/45

I think you'll agree with me that someone who receives an update notice from HACS, will download the latest offered version (0.2.0), and this will lead to confusion if nothing is clarified in the readme.

**Comment by regystro** [comment]
Don't know why you just deleted my last comment, since IMHO I was only trying to explain why people keeps asking and being confused. I was just offering a suggestion.

I think you'll agree with me that someone who receives an update notice from HACS, will download the latest offered version (0.2.0), and this will lead once again to confusion if nothing is clarified in the readme (e.g. _don't download 0.2.0, use "master" instead_, as @jsermer pointed out [here](https://github.com/custom-components/sensor.rpi_power/issues/45#issuecomment-672944266)).

Also I'm sad to hear that HA won't give you credit for your idea. 

Greetings.
