### ISSUE TITLE
Unfortunatelly can't see the sensor on 64-bit system

### ISSUE THREAD

**Issue by Pavel-Vovk** [custom-components/sensor.rpi_power#46]
System raspberry pi 8GB (64bit version of OS )

/config/configuration.yaml
...
hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true
...
sensor: !include_dir_merge_list includes/sensor
...
/config/includes/sensor/system.yaml
...
  - platform: rpi_power
    text_state: true
...

**Comment by swetoast** [comment]
yeah i wont be fixing this, wait for it to be merged into ha core
