### ISSUE TITLE
Failure codes missing

### ISSUE THREAD

**Issue by metbril** [custom-components/sensor.rpi_power#47]
My current binary sensor (luckily) is `off`, and the sensor doesn't have any attributes. I'm building automations and would like to know how to build a notification with the specific errors. There is not much documentation available in this repo. 

Can you please update the README with documentation of sensor values / attributes that we can expect? And an example of a notification?

**Comment by metbril** [comment]
I've browsed the commit history a bit and noticed that the component used to but no longer returns attributes with the specific error codes and error descriptions. These are helpful in troubleshooting.

Why have these been removed?

Would you consider reverting to this, or accept a PR?

**Comment by swetoast** [comment]
its being introduced into HA no more patches

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.

**Comment by metbril** [comment]
I'll wait for the official integration.
