### ISSUE TITLE
Please add support for the new SOFT_TEMP_LIMIT bit.

### ISSUE THREAD

**Issue by bosbefok** [custom-components/sensor.rpi_power#6]
For RPI3B+ please provide descriptive message for this throttled state rather than the default "There is a problem with your power supply or system." case.

New values are 0x80000 and 0x80008

Details here:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=224861

**Comment by swetoast** [comment]
Got some time coming up during christmas will take the time then to handle it.

**Comment by swetoast** [comment]
@bosbefok mind printing this out when 0x8 happens

`cat /sys/devices/platform/soc/soc:firmware/get_throttled`

**Comment by swetoast** [comment]
reopen if need be :)

**Comment by bosbefok** [comment]
cat /sys/devices/platform/soc/soc:firmware/get_throttled returns
80000
or
80008
