### ISSUE TITLE
Error message with new 0.88.0b0 of home assistant

### ISSUE THREAD

**Issue by Obicom** [custom-components/sensor.rpi_power#9]
The custom component rpi_power lead in a error with new ha version 0.88.0.
(architecture change of custom components) See new release note: https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/

Error:  2019-02-14 22:45:49 WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change sensor/rpi_power.py to rpi_power/sensor.py. This will stop working soon.

**Comment by swetoast** [comment]
It's not an error it's a warning and yes this add-on will update in due time
